// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "./pages/Home/Home.tsx": {
    id: "pages/Home/Home";
    page: "/";
  };
  "pages/debug-null.tsx": {
    id: "pages/debug-null";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
};